<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Pulse.Persistence\Pulse.Persistence.csproj" />
    <ProjectReference Include="..\Pulse.Domain\Pulse.Domain.csproj" />
  </ItemGroup>
</Project>
